package Vista;


import Modelo.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nicolás Acuña
 */
public class VentanaMenu extends javax.swing.JFrame {
    
    private final Region valparaiso;
    private final CSV administradorCSV;
    
    private VentanaAgregarLocal agregarLocal;
    private VentanaModificarDatosLocal modificarDatosLocal;
    private VentanaEliminarLocal eliminarLocal;
    private VentanaBuscarLocal buscarLocal;
    private VentanaMostrarLocales mostrarLocales;
    
    private VentanaAgregarPersona agregarPersona;
    private VentanaModificarDatosPersona modificarDatosPersona;
    private VentanaEliminarPersona eliminarPersona;
    private VentanaBuscarPersona buscarPersona;
    private VentanaMostrarVotantesLocal mostrarVotantesLocal;
    private VentanaMostrarVotantes mostrarVotantes;
    
    private VentanaMostrarLocalMasLleno mostrarLocalMasLleno;
    private VentanaMostrarVotantesNombreoApellido mostrarVotantesNombreoApellido;
    private VentanaMostrarNoVotantes mostrarNoVotantes;
   private VentanaMostrarSortNombresLocales mostrarSortNombresLocales;
   private VentanaMostrarSortRutsVotantes mostrarSortRutsVotantes;

    /**
     * Creates new form VentanaMenu
     * @param valparaiso región valparaiso
     * @param administradorCSV administrador de los CSV
     */
    public VentanaMenu(Region valparaiso, CSV administradorCSV) {
        initComponents();
        this.valparaiso = valparaiso;
        this.administradorCSV = administradorCSV;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonFuncion1 = new javax.swing.JButton();
        botonFuncion2 = new javax.swing.JButton();
        botonFuncion3 = new javax.swing.JButton();
        botonFuncion4 = new javax.swing.JButton();
        botonFuncion5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonFuncion6 = new javax.swing.JButton();
        botonFuncion7 = new javax.swing.JButton();
        botonFuncion8 = new javax.swing.JButton();
        botonFuncion9 = new javax.swing.JButton();
        botonFuncion10 = new javax.swing.JButton();
        botonFuncion11 = new javax.swing.JButton();
        botonFuncion12 = new javax.swing.JButton();
        botonFuncion13 = new javax.swing.JButton();
        botonFuncion14 = new javax.swing.JButton();
        botonFuncion15 = new javax.swing.JButton();
        botonFuncion16 = new javax.swing.JButton();
        botonFuncion17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonFuncion1.setText("Agregar Local");
        botonFuncion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion1ActionPerformed(evt);
            }
        });

        botonFuncion2.setText("Modificar Datos Local");
        botonFuncion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion2ActionPerformed(evt);
            }
        });

        botonFuncion3.setText("Eliminar Local");
        botonFuncion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion3ActionPerformed(evt);
            }
        });

        botonFuncion4.setText("Buscar Local");
        botonFuncion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion4ActionPerformed(evt);
            }
        });

        botonFuncion5.setText("Mostrar Locales de la region en detalle");
        botonFuncion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion5ActionPerformed(evt);
            }
        });

        jLabel1.setText("GESTION DE VOTANTES-LOCALES DE VOTACIÓN");

        botonFuncion6.setText("Agregar Persona");
        botonFuncion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion6ActionPerformed(evt);
            }
        });

        botonFuncion7.setText("Modificar Datos Persona");
        botonFuncion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion7ActionPerformed(evt);
            }
        });

        botonFuncion8.setText("Eliminar Persona");
        botonFuncion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion8ActionPerformed(evt);
            }
        });

        botonFuncion9.setText("Buscar Persona");
        botonFuncion9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion9ActionPerformed(evt);
            }
        });

        botonFuncion10.setText("Mostrar Votantes de un local");
        botonFuncion10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion10ActionPerformed(evt);
            }
        });

        botonFuncion11.setText("Mostrar Votantes de la region");
        botonFuncion11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion11ActionPerformed(evt);
            }
        });

        botonFuncion12.setText("Mostrar Local con más votantes");
        botonFuncion12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion12ActionPerformed(evt);
            }
        });

        botonFuncion13.setText("Mostrar Votantes de un mismo nombre o apellido");
        botonFuncion13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion13ActionPerformed(evt);
            }
        });

        botonFuncion14.setText("Mostrar No Votantes de la region");
        botonFuncion14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion14ActionPerformed(evt);
            }
        });

        botonFuncion15.setText("Exportar archivo *.csv");
        botonFuncion15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion15ActionPerformed(evt);
            }
        });

        botonFuncion16.setText("Mostrar nombres de Locales en orden alfabetico");
        botonFuncion16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion16ActionPerformed(evt);
            }
        });

        botonFuncion17.setText("Mostrar Votantes de todos los Locales en orden alfabetico");
        botonFuncion17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFuncion17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFuncion1)
                    .addComponent(botonFuncion2)
                    .addComponent(botonFuncion3)
                    .addComponent(botonFuncion4)
                    .addComponent(botonFuncion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFuncion6)
                    .addComponent(botonFuncion7)
                    .addComponent(botonFuncion8)
                    .addComponent(botonFuncion9)
                    .addComponent(botonFuncion10)
                    .addComponent(botonFuncion11))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFuncion16)
                    .addComponent(botonFuncion17)
                    .addComponent(botonFuncion15)
                    .addComponent(botonFuncion14)
                    .addComponent(botonFuncion13)
                    .addComponent(botonFuncion12))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(botonFuncion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonFuncion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonFuncion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonFuncion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonFuncion5)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonFuncion6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonFuncion12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFuncion17)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFuncion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion1ActionPerformed
       this.setVisible(false);
       this.agregarLocal = new VentanaAgregarLocal(this, valparaiso);
       agregarLocal.setVisible(true);
    }//GEN-LAST:event_botonFuncion1ActionPerformed

    private void botonFuncion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion2ActionPerformed
        this.setVisible(false);
        this.modificarDatosLocal = new VentanaModificarDatosLocal(this, valparaiso);
        modificarDatosLocal.setVisible(true);
    }//GEN-LAST:event_botonFuncion2ActionPerformed

    private void botonFuncion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion3ActionPerformed
        this.setVisible(false);
        this.eliminarLocal = new VentanaEliminarLocal(this, valparaiso);
        eliminarLocal.setVisible(true);
    }//GEN-LAST:event_botonFuncion3ActionPerformed

    private void botonFuncion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion4ActionPerformed
        this.setVisible(false);
        this.buscarLocal = new VentanaBuscarLocal(this, valparaiso);
        buscarLocal.setVisible(true);
    }//GEN-LAST:event_botonFuncion4ActionPerformed

    private void botonFuncion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion5ActionPerformed
        this.setVisible(false);
        this.mostrarLocales = new VentanaMostrarLocales(this, valparaiso);
        mostrarLocales.setVisible(true);
    }//GEN-LAST:event_botonFuncion5ActionPerformed

    private void botonFuncion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion6ActionPerformed
        this.setVisible(false);
        this.agregarPersona = new VentanaAgregarPersona(this, valparaiso);
        agregarPersona.setVisible(true);
    }//GEN-LAST:event_botonFuncion6ActionPerformed

    private void botonFuncion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion7ActionPerformed
        this.setVisible(false);
        this.modificarDatosPersona = new VentanaModificarDatosPersona(this, valparaiso);
        modificarDatosPersona.setVisible(true);
    }//GEN-LAST:event_botonFuncion7ActionPerformed

    private void botonFuncion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion8ActionPerformed
        this.setVisible(false);
        this.eliminarPersona = new VentanaEliminarPersona(this, valparaiso);
        eliminarPersona.setVisible(true);
    }//GEN-LAST:event_botonFuncion8ActionPerformed

    private void botonFuncion9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion9ActionPerformed
        this.setVisible(false);
        this.buscarPersona = new VentanaBuscarPersona(this, valparaiso);
        buscarPersona.setVisible(true);
    }//GEN-LAST:event_botonFuncion9ActionPerformed

    private void botonFuncion10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion10ActionPerformed
        this.setVisible(false);
        this.mostrarVotantesLocal = new VentanaMostrarVotantesLocal(this, valparaiso);
        mostrarVotantesLocal.setVisible(true);
    }//GEN-LAST:event_botonFuncion10ActionPerformed

    private void botonFuncion11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion11ActionPerformed
        this.setVisible(false);
        this.mostrarVotantes = new VentanaMostrarVotantes(this, valparaiso);
        mostrarVotantes.setVisible(true);
    }//GEN-LAST:event_botonFuncion11ActionPerformed

    private void botonFuncion12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion12ActionPerformed
        this.setVisible(false);
        this.mostrarLocalMasLleno = new VentanaMostrarLocalMasLleno(this, valparaiso);
        mostrarLocalMasLleno.setVisible(true);
    }//GEN-LAST:event_botonFuncion12ActionPerformed

    private void botonFuncion13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion13ActionPerformed
        this.setVisible(false);
        this.mostrarVotantesNombreoApellido = new VentanaMostrarVotantesNombreoApellido(this, valparaiso);
        mostrarVotantesNombreoApellido.setVisible(true);
    }//GEN-LAST:event_botonFuncion13ActionPerformed

    private void botonFuncion14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion14ActionPerformed
        this.setVisible(false);
        this.mostrarNoVotantes = new VentanaMostrarNoVotantes(this, valparaiso);
        mostrarNoVotantes.setVisible(true);
    }//GEN-LAST:event_botonFuncion14ActionPerformed

    private void botonFuncion15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion15ActionPerformed
        administradorCSV.exportarCSV("datosExportar.csv", valparaiso);
    }//GEN-LAST:event_botonFuncion15ActionPerformed

    private void botonFuncion16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion16ActionPerformed
       this.setVisible(false);
       this.mostrarSortNombresLocales = new VentanaMostrarSortNombresLocales(this,valparaiso);
       mostrarSortNombresLocales.setVisible(true);
    }//GEN-LAST:event_botonFuncion16ActionPerformed

    private void botonFuncion17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFuncion17ActionPerformed
       this.setVisible(false);
       this.mostrarSortRutsVotantes = new VentanaMostrarSortRutsVotantes(this,valparaiso);
       mostrarSortRutsVotantes.setVisible(true);
    }//GEN-LAST:event_botonFuncion17ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFuncion1;
    private javax.swing.JButton botonFuncion10;
    private javax.swing.JButton botonFuncion11;
    private javax.swing.JButton botonFuncion12;
    private javax.swing.JButton botonFuncion13;
    private javax.swing.JButton botonFuncion14;
    private javax.swing.JButton botonFuncion15;
    private javax.swing.JButton botonFuncion16;
    private javax.swing.JButton botonFuncion17;
    private javax.swing.JButton botonFuncion2;
    private javax.swing.JButton botonFuncion3;
    private javax.swing.JButton botonFuncion4;
    private javax.swing.JButton botonFuncion5;
    private javax.swing.JButton botonFuncion6;
    private javax.swing.JButton botonFuncion7;
    private javax.swing.JButton botonFuncion8;
    private javax.swing.JButton botonFuncion9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
