package Vista;


import Modelo.Region;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana mostrar no votantes de la región de valparaiso
 * @author Nicolás Acuña
 */
public class VentanaMostrarNoVotantes extends javax.swing.JFrame {
    
    private final JFrame menu;
    private final Region valparaiso;

    /**
     * Creates new form VentanaMostrarNoVotantes
     * @param menu Ventana menu
     * @param valparaiso región de valparaiso
     */
    public VentanaMostrarNoVotantes(JFrame menu, Region valparaiso) {
        initComponents();
        this.menu = menu;
        this.valparaiso = valparaiso;
        this.setLocationRelativeTo(null);
        
        this.mostrarNoVotantes();
    }
    
    public void mostrarNoVotantes(){
        DefaultTableModel modelo = (DefaultTableModel) tablaNoVotantes.getModel();
        
        String[] rutsNoVotantes = valparaiso.obtenerRutsNoVotantes();
        int cantidadNoVotantes = rutsNoVotantes.length;

        Object[] datosFila = new Object[5];
        
        for(int i = 0; i < cantidadNoVotantes; i++){
            String datosNoVotante = valparaiso.obtenerDatosNoVotante(rutsNoVotantes[i]);
            String[] arregloDatosNoVotante = datosNoVotante.split(",");
            
            datosFila[0] = arregloDatosNoVotante[0];
            datosFila[1] = arregloDatosNoVotante[1];
            datosFila[2] = arregloDatosNoVotante[2];
            datosFila[3] = arregloDatosNoVotante[3];
            datosFila[4] = arregloDatosNoVotante[4];
            
            
            modelo.addRow(datosFila);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNoVotantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver al Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("No Votantes de la región de Valparaíso");

        tablaNoVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rut", "Comuna", "Dirección", "Razón"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaNoVotantes);
        if (tablaNoVotantes.getColumnModel().getColumnCount() > 0) {
            tablaNoVotantes.getColumnModel().getColumn(0).setMinWidth(300);
            tablaNoVotantes.getColumnModel().getColumn(0).setMaxWidth(300);
            tablaNoVotantes.getColumnModel().getColumn(1).setMinWidth(120);
            tablaNoVotantes.getColumnModel().getColumn(1).setMaxWidth(120);
            tablaNoVotantes.getColumnModel().getColumn(2).setMinWidth(175);
            tablaNoVotantes.getColumnModel().getColumn(2).setMaxWidth(175);
            tablaNoVotantes.getColumnModel().getColumn(3).setMinWidth(250);
            tablaNoVotantes.getColumnModel().getColumn(3).setMaxWidth(250);
            tablaNoVotantes.getColumnModel().getColumn(4).setMinWidth(150);
            tablaNoVotantes.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaNoVotantes;
    // End of variables declaration//GEN-END:variables
}
