package Vista;

import Modelo.Region;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana mostrar votantes de la región de valparaiso
 * @author Nicolás Acuña
 */
public class VentanaMostrarVotantes extends javax.swing.JFrame {
    
    private final JFrame menu;
    private final Region valparaiso;

    /**
     * Creates new form VentanaMostrarVotantes
     * @param menu Ventana menu
     * @param valparaiso región de valparaiso
     */
    public VentanaMostrarVotantes(JFrame menu, Region valparaiso) {
        initComponents();
        this.menu = menu;
        this.valparaiso = valparaiso;
        this.setLocationRelativeTo(null);
        
        this.mostrarVotantes();
        
        
    }
    
    public void mostrarVotantes(){
        DefaultTableModel modelo = (DefaultTableModel) tablaVotantes.getModel();
        
        String[] rutsVotantes = valparaiso.obtenerRutsVotantes();
        
        Object[] datosFila = new Object[7];
            
        for(int i = 0; i < rutsVotantes.length; i++){     
            String datosVotante = valparaiso.obtenerDatosVotante(rutsVotantes[i]);
            String [] arregloDatosVotante = datosVotante.split(",");
            
            datosFila[0] = arregloDatosVotante[0];
            datosFila[1] = arregloDatosVotante[1];
            datosFila[2] = arregloDatosVotante[2];
            datosFila[3] = arregloDatosVotante[3];
            datosFila[4] = arregloDatosVotante[5];
            datosFila[5] = arregloDatosVotante[6];
            datosFila[6] = arregloDatosVotante[4];
            
            modelo.addRow(datosFila);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVotantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver al menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Votantes de la región de Valparaiso");

        jScrollPane2.setBorder(new javax.swing.border.MatteBorder(null));

        tablaVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rut", "Comuna", "Dirección", "Local", "Dirección Local", "Mesa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVotantes);
        if (tablaVotantes.getColumnModel().getColumnCount() > 0) {
            tablaVotantes.getColumnModel().getColumn(0).setMinWidth(250);
            tablaVotantes.getColumnModel().getColumn(0).setMaxWidth(250);
            tablaVotantes.getColumnModel().getColumn(1).setMinWidth(120);
            tablaVotantes.getColumnModel().getColumn(1).setMaxWidth(120);
            tablaVotantes.getColumnModel().getColumn(2).setMinWidth(150);
            tablaVotantes.getColumnModel().getColumn(2).setMaxWidth(150);
            tablaVotantes.getColumnModel().getColumn(3).setMinWidth(175);
            tablaVotantes.getColumnModel().getColumn(3).setMaxWidth(175);
            tablaVotantes.getColumnModel().getColumn(4).setMinWidth(200);
            tablaVotantes.getColumnModel().getColumn(4).setMaxWidth(200);
            tablaVotantes.getColumnModel().getColumn(5).setMinWidth(175);
            tablaVotantes.getColumnModel().getColumn(5).setMaxWidth(175);
            tablaVotantes.getColumnModel().getColumn(6).setMinWidth(60);
            tablaVotantes.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(523, 523, 523))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVotantes;
    // End of variables declaration//GEN-END:variables
}
